// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbO60z-Yc40sN5T8Hx-wLYMao756OpZlg',
    appId: '1:448168991519:android:30ee71a05d8f909cb76e2a',
    messagingSenderId: '448168991519',
    projectId: 'ur-health-cd3fb',
    storageBucket: 'ur-health-cd3fb.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASKu1QLX04a-wEsnz_MhRl2ZWmYiChgKo',
    appId: '1:448168991519:web:145fa8b10ef6e17ab76e2a',
    messagingSenderId: '448168991519',
    projectId: 'ur-health-cd3fb',
    authDomain: 'ur-health-cd3fb.firebaseapp.com',
    storageBucket: 'ur-health-cd3fb.firebasestorage.app',
    measurementId: 'G-K7K4K31RCK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIqOVLE-XkSWPclgu3JswG_OsM51P3leI',
    appId: '1:448168991519:ios:f3c7e894fb09a76cb76e2a',
    messagingSenderId: '448168991519',
    projectId: 'ur-health-cd3fb',
    storageBucket: 'ur-health-cd3fb.firebasestorage.app',
    androidClientId: '448168991519-k4c6ler3rcglrmroq6fmv1283rc7l86k.apps.googleusercontent.com',
    iosClientId: '448168991519-c5she87dcss9kc1ffttdaghcibeav9bs.apps.googleusercontent.com',
    iosBundleId: 'com.example.urHealth',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIqOVLE-XkSWPclgu3JswG_OsM51P3leI',
    appId: '1:448168991519:ios:f3c7e894fb09a76cb76e2a',
    messagingSenderId: '448168991519',
    projectId: 'ur-health-cd3fb',
    storageBucket: 'ur-health-cd3fb.firebasestorage.app',
    androidClientId: '448168991519-k4c6ler3rcglrmroq6fmv1283rc7l86k.apps.googleusercontent.com',
    iosClientId: '448168991519-c5she87dcss9kc1ffttdaghcibeav9bs.apps.googleusercontent.com',
    iosBundleId: 'com.example.urHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASKu1QLX04a-wEsnz_MhRl2ZWmYiChgKo',
    appId: '1:448168991519:web:36a8e509db178c64b76e2a',
    messagingSenderId: '448168991519',
    projectId: 'ur-health-cd3fb',
    authDomain: 'ur-health-cd3fb.firebaseapp.com',
    storageBucket: 'ur-health-cd3fb.firebasestorage.app',
    measurementId: 'G-YCEBLH70V8',
  );

}